services:
  queue-server:
    container_name: queue-server
    build:
      dockerfile: Dockerfile
    volumes:
      - "./volumes/app:/app"
    environment:
      DATABASE: "/app/db.sqlite"
      JWT_SECRET: prueba
      ADDRESS: "0.0.0.0:8080"
    ports:
      - "8080:8080"
